# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - covr
addons:
  apt:
    packages:
    - libudunits2-dev
    - libproj-dev
    - libgeos-dev
    - libgdal-dev
    - libnetcdf-dev
    - netcdf-bin
after_success:
  - Rscript -e 'library(covr); codecov()'
